### PR TITLE
Update to Vapor 0.18, Fluent 0.11 and Swift GM

### PR DESCRIPTION
**Pull request by adriencanterot**
_PR does not build_

Hi everyone, I just updated the sqlite-provider package, it works with Vapor 0.17. It does not build but since I made PRs on vapor/sqlite, vapor/sqlite-driver and vapor/sqlite-provider to keep them up tp date, updating the version of each package should make it work with Vapor.
## New
- License file
- Tests
## Updated
- Provider protocol ( can now be used with Config )
- .swift-version to 09-06
- README.md comes with proper instruction on how to use the provider with à Config file
## Opinion

For the `sqlite.json` file
I imagined a simple structure as follows : 

``` json
{
     "path": "Database/main.sqlite"
} 
```

Thank you for reviewing this proposal

### CODE REVIEW

**Comment by tanner0101** [comment]
This looks good. So we need to merge the PRs to sqlite first then sqlite-driver?

**Comment by adriencanterot** [comment]
That's right, once the sqlite PR is tagged, sqlite-driver should build, then tagged, then this one should build as well.
I might need to have a last look at sqlite-driver though, I'll comment again when ready.

**Comment by tanner0101** [comment]
SQLite 0.3 is tagged: https://github.com/vapor/sqlite/releases/tag/0.3.0

**Comment by adriencanterot** [comment]
Hi @tannernelson , this one is ready to be merged and tagged as well. Ready for GM and Vapor 0.18.

**Comment by Tanner** [comment]
Just to let you know, you're pinging me, not @tannernelson.

**Comment by adriencanterot** [comment]
Oh sorry, I thought it worked like Facebook or something, my bad :/

**Pull request merged**
