### PR TITLE
Update to Vapor 0.14 with new droplet syntax

### PR DESCRIPTION
**Pull request by adriencanterot**
Hi
This is just an update to resolve dependency conflicts and new syntax in vapor 0.14

### CODE REVIEW

**Comment by tanner0101** [comment]
Looks like the build is failing from a Travis yml error. Copying the `before_script` from Vapor's travis.yml would fix.

**Comment by adriencanterot** [comment]
It worked ! also, I removed the lines that were probably copied from vapor-mysql travis.yml which had no use with SQLite
Thanks

**Comment by tanner0101** [comment]
Awesome, thanks!

**Comment by tanner0101** [comment]
Vapor SQLite 0.2 is now available.
https://github.com/qutheory/vapor-sqlite/releases/tag/0.2.0

**Pull request merged**
