### PR TITLE
Update to new version of Vapor

### PR DESCRIPTION
**Pull request by kafejo**

### CODE REVIEW

**Comment by tanner0101** [comment]
Looks like the `sqlite-driver` package needs to be updated first.

**Comment by adriencanterot** [comment]
Yes I'm almost done with that ! Will submit a PR soon to sqlite-driver

**Comment by smumriak** [comment]
Hey, is this PR still relevant? cc @adriencanterot

**Comment by adriencanterot** [comment]
Yes it is ! 
I submitted a PR for the sqlite-driver package that is not complete however, [you can take a look there](https://github.com/vapor/sqlite-driver/pull/10)
It is not ready to merge yet as there is a little more work to do regarding joined queries.
Plus the sqlite package needs an update as well.
As I understood, for now, it is mostly the mysql package that is given the most attention in order to have Vapor working with at least 1 DB engine. However, it'd be nice to have sqlite working for when Vapor 1.0 comes out !

**Comment by tanner0101** [comment]
We'll definitely have SQLite support for the 1.0 release.

**Comment by adriencanterot** [comment]
Hi @kafejo, just making a reference to #4  since there has been a little work done with the provider.

**Pull request closed without merging**
